### ISSUE TITLE
Invalid path alias: @barrelstrength/sproutbase/controllers

### ISSUE THREAD

**Issue by urbantrout** [barrelstrength/craft-sprout-base#5]
After installing sprout-forms on Craft CMS 3 I get the following error when running ./craft on the command line:

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @barrelstrength/sproutbase/controllers'

in /var/www/html/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Module.php(257): yii\BaseYii::getAlias('@barrelstrength...')
#1 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(246): yii\base\Module->getControllerPath()
#2 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(241): yii\console\controllers\HelpController->getModuleCommands(Object(barrelstrength\sproutbase\SproutBase))
#3 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(175): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#4 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(187): yii\console\controllers\HelpController->getCommands()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(293): yii\console\controllers\HelpController->getCommandDescriptions()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#7 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array,Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/html/craft(22): yii\base\Application->run()
#16 {main}
```

My Setup:

PHP 7.2.4
Craft CMS 3.0.5

Using this Docker image https://hub.docker.com/r/urbantrout/craftcms/

**Comment by BenParizek** [comment]
We can recreate this. Will update when we have a solution.

**Comment by BenParizek** [comment]
Related: https://github.com/barrelstrength/craft-sprout-forms/issues/91
